import { translate } from "./locale.mjs";
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function csvReport(rows){const fields=['server','collection_id','captured_at','kind','name','pvp','pk','rank','clan','payload_json','source_json'];return fields.map(escapeCsv).join(',')+'\n'+rows.map(r=>fields.map(k=>escapeCsv(r[k])).join(',')).join('\n')+'\n';}
function escapeCsv(value){return '"'+String(value??'').replace(/"/g,'""')+'"';}
export function htmlReport(rows,scope,locale='en'){
 const t=(key,values)=>translate(locale,key,values);
 const labels=JSON.stringify({matches:t("{count} matching sampled observations",{count:"{count}"}),fields:Object.fromEntries(Object.entries({server:"Server",captured_at:"Observed (UTC)",kind:"Entity type",name:"Name",pvp:"PvP",pk:"PK",rank:"Rank",clan:"Clan"}).map(([field,key])=>[field,t(key)]))}).replace(/</g,"\\u003c");
 const sample=rows.length>10000?rows.filter((_,i)=>i%Math.ceil(rows.length/10000)===0):rows;
 const data=JSON.stringify(sample).replace(/</g,'\\u003c');
 return `<!doctype html><html lang="${escapeHtml(locale)}"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>${escapeHtml(t("Lu4 historical export"))}</title>
 <style>body{font:16px system-ui;max-width:1200px;margin:30px auto;padding:16px;background:#111827;color:#eee}input,button{padding:8px;margin:4px}table{width:100%;border-collapse:collapse}td,th{padding:6px;text-align:left;border-bottom:1px solid #374151}svg{width:100%;height:240px;background:#1f2937}button{cursor:pointer}caption{text-align:left}</style>
 <h1>${escapeHtml(t("Lu4 historical export"))}</h1><p>${escapeHtml(scope)}</p><p>${escapeHtml(t("Recorded observations: {total}. Report sample: {sample}. CSV contains every exported observation.",{total:rows.length,sample:sample.length}))}</p><p>${escapeHtml(t("Charts show sampled observations. Gaps do not establish continuous ranking presence."))}</p>
 <label>${escapeHtml(t("Search"))} <input id="search"></label><label>${escapeHtml(t("From"))} <input id="from" type="date"></label><label>${escapeHtml(t("To"))} <input id="to" type="date"></label><p id="count"></p><svg id="chart" viewBox="0 0 1000 240" role="img" aria-label="${escapeHtml(t("PvP history"))}"></svg><p id="legend"></p><table><caption>${escapeHtml(t("Up to 500 matching rows. Select a header to sort."))}</caption><thead id="head"></thead><tbody id="body"></tbody></table>
 <script type="application/json" id="data">${data}</script><script>
 const labels=${labels};
 const rows=JSON.parse(document.getElementById('data').textContent),fields=['server','captured_at','kind','name','pvp','pk','rank','clan'];let sort='captured_at',direction=1;
 const head=document.getElementById('head'),tr=document.createElement('tr');for(const field of fields){const th=document.createElement('th'),button=document.createElement('button');button.textContent=labels.fields[field];button.onclick=()=>{direction=sort===field?-direction:1;sort=field;render()};th.append(button);tr.append(th)}head.append(tr);
 function render(){const search=document.getElementById('search').value.toLowerCase(),from=document.getElementById('from').value,to=document.getElementById('to').value;const filtered=rows.filter(r=>(r.name+' '+r.clan+' '+r.server).toLowerCase().includes(search)&&(!from||r.captured_at.slice(0,10)>=from)&&(!to||r.captured_at.slice(0,10)<=to));document.getElementById('count').textContent=labels.matches.replace('{count}',filtered.length);const body=document.getElementById('body');body.replaceChildren();filtered.sort((a,b)=>String(a[sort]??'').localeCompare(String(b[sort]??''),undefined,{numeric:true})*direction);for(const row of filtered.slice(0,500)){const tr=document.createElement('tr');for(const field of fields){const td=document.createElement('td');td.textContent=row[field]??'—';tr.append(td)}body.append(tr)}
 const svg=document.getElementById('chart');svg.replaceChildren();const series=new Map();for(const row of filtered){if(!['player','clan'].includes(row.kind)||row.pvp==null)continue;const key=row.server+' / '+row.name;if(!series.has(key))series.set(key,[]);series.get(key).push(row)}const selected=[...series.values()].slice(0,9),values=selected.flat();document.getElementById('legend').textContent=selected.map(line=>line[0].server+' / '+line[0].name).join(' · ');if(!values.length)return;const low=Math.min(...values.map(r=>Number(r.pvp))),high=Math.max(...values.map(r=>Number(r.pvp))),start=Math.min(...values.map(r=>Date.parse(r.captured_at))),end=Math.max(...values.map(r=>Date.parse(r.captured_at)));for(const [text,x,y] of [[high,20,15],[low,20,237],[new Date(start).toISOString().slice(0,10),60,237],[new Date(end).toISOString().slice(0,10),850,237]]){const label=document.createElementNS('http://www.w3.org/2000/svg','text');label.textContent=text;label.setAttribute('x',x);label.setAttribute('y',y);label.setAttribute('fill','#ddd');label.setAttribute('font-size','12');svg.append(label)}selected.forEach((line,i)=>{line.sort((a,b)=>Date.parse(a.captured_at)-Date.parse(b.captured_at));for(const row of line.filter((_,n)=>n%Math.max(1,Math.ceil(line.length/500))===0)){const dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',20+960*(Date.parse(row.captured_at)-start)/(end-start||1));dot.setAttribute('cy',220-200*(Number(row.pvp)-low)/(high-low||1));dot.setAttribute('r','2');dot.setAttribute('fill',['#38bdf8','#f472b6','#a3e635','#fb923c','#c084fc','#facc15','#2dd4bf','#f87171','#818cf8'][i]);const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=row.name+' '+row.captured_at+' PvP '+row.pvp;dot.append(title);svg.append(dot)}})}
 for(const id of ['search','from','to'])document.getElementById(id).oninput=render;render();</script></html>`;
}
